/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "com/cjmobileapps/quidditchplayers/model/Status.h"

#ifdef __cplusplus
extern "C" {
#endif

// Function declaration for JNI method stringFromJNI
JNIEXPORT jstring JNICALL Java_com_cjmobileapps_quidditchplayersandroid_data_MockDataFromCPP_stringFromJNI
        (JNIEnv *, jobject);

// Function declaration for JNI method stringFromJNI2
void JNICALL Java_com_cjmobileapps_quidditchplayersandroid_data_MockDataFromCPP_stringFromJNI2();

// Declaration of the 'blah' function
void blah();
#ifdef __cplusplus
}
#endif
